CREATE TABLE loteria;

CREATE TABLE users (
id INT (11),
username VARCHAR(20),
password VARCHAR(20)
);

ALTER TABLE users
MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT,
ADD PRIMARY KEY (id);

ALTER TABLE users ADD created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;